baseURL = "https://www.afterschoolspecial.band/"
languageCode = "en-us"
title = "After School Special"
buildFuture = true

[params]
  tagline = "A teachers' band, playing since the 90s"
  facebook = "https://www.facebook.com/afterschoolspecial101"
  instagram = "https://www.instagram.com/afterschoolspecialband125/"
  youtube = "https://www.youtube.com/@AfterSchoolSpecialBand"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Members"
  url = "/members/"
  weight = 2

[[menu.main]]
  name = "Song List"
  url = "/songlist/"
  weight = 3

[[menu.main]]
  name = "Shows"
  url = "/gigs/"
  weight = 4

[[menu.main]]
  name = "Video"
  url = "/video/"
  weight = 5

[[menu.main]]
  name = "Photos"
  url = "/photos/"
  weight = 6

[[menu.main]]
  name = "Contact Us"
  url = "/contact/"
  weight = 7
